# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
# h2 Database
  h2:
    console:
      enabled: true
# Server configuration
server:
  port: 8080
